### ISSUE TITLE
Vertical graph

### ISSUE THREAD

**Issue by wietseneven** [q-m/d3.chart.sankey#8]
Is it possible to make to graph go vertical in stead of horizontal? If not integrated, where do I have to look to make it work myself?

**Comment by wvengen** [comment]
What about putting it in an svg transform for rotation? Or would you like the labels to be unrotated too? (You may try to fiddle with css to do so, but it's hard to guarentee the labels won't overlap).

**Comment by wietseneven** [comment]
Yes that's the best solution for now I think, thanks!
